### ISSUE TITLE
v1.12.0: Size of widget not respected for Fixed layout

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#1006]
### Current Behavior

If I use the size attribut of a widget to place two widgets side by side in one row, this is no longer working with v1.12.0 in fixed layout.
This was working fine in v.1.11.1!

### Expected Behavior

Widgets can be places side by side with the size property.

### Steps To Reproduce

try this sample flow
```[{"id":"dcc15970006a41ac","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"3f4a2740a6e91c95","type":"ui-text","z":"dcc15970006a41ac","group":"9b597a79245141ec","order":0,"width":"3","height":"1","name":"","label":"left","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":410,"y":420,"wires":[]},{"id":"01ddda3a3b9eb8b3","type":"ui-text","z":"dcc15970006a41ac","group":"9b597a79245141ec","order":0,"width":"3","height":"1","name":"","label":"right","format":"{{msg.payload}}","layout":"row-spread","style":false,"font":"","fontSize":16,"color":"#717171","className":"","x":410,"y":460,"wires":[]},{"id":"781f36df75997293","type":"inject","z":"dcc15970006a41ac","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":230,"y":440,"wires":[["3f4a2740a6e91c95","01ddda3a3b9eb8b3"]]},{"id":"809d7fc2ea9e1053","type":"ui-button","z":"dcc15970006a41ac","group":"9b597a79245141ec","name":"","label":"button","order":0,"width":"3","height":"1","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":350,"y":520,"wires":[[]]},{"id":"9b597a79245141ec","type":"ui-group","name":"Test-Group","page":"a12cc971e8c42860","width":"6","height":"1","order":-1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"a12cc971e8c42860","type":"ui-page","name":"Test-Page","ui":"fd06eabec55c4e5d","path":"/page25","icon":"home","layout":"flex","theme":"a965ccfef139317a","order":-1,"className":"","visible":"true","disabled":"false"},{"id":"fd06eabec55c4e5d","type":"ui-base","name":"Dashboard 2.0","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false,"navigationStyle":"default","titleBarStyle":"fixed"},{"id":"a965ccfef139317a","type":"ui-theme","name":"Default","colors":{"surface":"#6db046","primary":"#32cd32","bgPage":"#000000","groupBg":"#333333","groupOutline":"#616161"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]```

The text fields should be side by side with a half group width and the button should also be half width!

it looks like this in `fixed` layout:
![grafik](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/500f0a5c-540f-4812-a63a-2f375e33ff13)
and in `grid` layout correctly:
![grafik](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/e1e23ae7-3a90-4b2a-96f2-8cc8106209bb)

### Environment

- Dashboard version: v1.12.0
- Node-RED version: 4.0.0
- Node.js version: 20.15
- npm version:
- Platform/OS: Raspberry OS
- Browser: Firefox, Win10

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by Soiski71** [comment]
Is there a way to downgrade to version 11.1. as all my layouts are now "wrong" and functionalities that I need (and working were on 11.1 version already).  If I download manually the version 11.1 from your pages ( and rename the file ending tar.gz to tgz ) and then trying to install it manually from the pallet manager .
![image](https://github.com/FlowFuse/node-red-dashboard/assets/59532263/15c19959-fc51-4b2a-84f6-1e06589a3b6a)

I get following error:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/59532263/b40fd2da-5f3c-47f6-9d2b-f1e8a794b7c5)

and no special log info:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/59532263/d0a151ba-124f-461c-8807-d3c347e2eddf)

is it possible some how differently ?

**Comment by joepavitt** [comment]
I will try and get the fix released this afternoon.

I already have the [Pull Request](https://github.com/FlowFuse/node-red-dashboard/pull/1007) open, just need @cstns to review

**Comment by joepavitt** [comment]
@Soiski71 this is now fixed in `1.12.1`

**Comment by colinl** [comment]
In fact I think it is not fully fixed.  The test flow above works on a laptop, or a mobile device in landscape mode, but in portrait mode the widgets appear as in the first post.  In 1.11.1 they show correctly side by side.
See also issue #1021 which I suspect is the same problem.
