### ISSUE TITLE
A subflow containing a ui node, packaged as a subflow, does not appear in dashboard config panel

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#722]
### Current Behavior

If a subflow containing a ui-template is packaged as a module and installed then the node does function correctly, but the widget does not appear in the dashboard panel.

### Expected Behavior

It should appear in the panel.

### Steps To Reproduce

Install this node directly from github using
`npm install colinl/node-red-dropdown-cdl`
Restart node-red and instantiate the node Dropdown CDL, which appears in the Function section.
Open the node and select a Group.  Note - select the correct group as due to [another problem](https://discourse.nodered.org/t/node-red-4-0-0-beta-1-released/86433/18) it is not possible to get back into the config again.
Deploy.  The dropdown appears in the dashboard but not in the dashboard config panel.

### Environment

- Dashboard version: 1.6.1
- Node-RED version: 4.0.0-Beta.1
- Node.js version:20
- npm version:
- Platform/OS: Ubuntu on laptop
- Browser: Edge

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by Steve-Mcl** [comment]
Colin, I _think_ this might resolved in beta.2.  i will hold of on triage of this item until I can assess this. 

Please update this issue if you happen to get to it before me.

Thanks for the feedback

**Comment by colinl** [comment]
With NR 4.0.0 Beta.2 and dashboard 1.7.0 the node still does not appear in the dashboard panel, but does appear in the dashboard.
